name: Node.js CI Demo

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Lấy code từ repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js (chọn version bạn dùng, ví dụ 18)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Cài dependencies
      - name: Install dependencies
        run: npm install

      # Build (nếu có script build trong package.json)
      - name: Build project
        run: npm run build --if-present

      # Demo chạy app (chạy 5 giây rồi kill để CI không treo)
      - name: Start app
        run: |
          npm start &
          sleep 5
          kill $!
